ALTER TABLE promotion_usages
  ADD COLUMN IF NOT EXISTS promo_code VARCHAR(255),
  ADD COLUMN IF NOT EXISTS discount_type VARCHAR(255),
  ADD COLUMN IF NOT EXISTS discount_value INT,
  ADD COLUMN IF NOT EXISTS is_remake BOOLEAN,
  ADD COLUMN IF NOT EXISTS remake_count INT,
  ADD COLUMN IF NOT EXISTS applied_conditions JSONB,
  ADD COLUMN IF NOT EXISTS applied_at TIMESTAMP;
